[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
prediction_market = "A3sWyZrffMAYLf84384gvWDvxdyE5YYfWBmbhP2GfuE5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/haji/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
